repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
      - id: check-toml
      - id: end-of-file-fixer
        exclude: 'docs\/source\/examples\/metabase_token'
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: 'tests\/(helpers|setup_metabase).py'
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: 'metabase_tools\/\S*.py'
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        files: 'metabase_tools\/\S*.py'
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        files: 'metabase_tools\/\S*.py'
        types: [python]
        args: ["--strict"]
