version: "3.9"

services:
  metabase:
    image: metabase/metabase:v0.44.6
    ports:
      - 3000:3000
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
  mbt-setup:
    build: .
    depends_on:
      - metabase
      - mailhog
    command: poetry run python setup_metabase.py
