name: Publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10 on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry config virtualenvs.in-project true
          poetry config installer.parallel true
          poetry check
      - name: Install dependencies
        run: poetry install --no-interaction --with dev,docs
        continue-on-error: true
      - name: Fix dependency errors
        run: poetry install --no-interaction --with dev,docs
      - name: Build HTML
        run: poetry run sphinx-build -W -a -E -b html docs/source/ docs/build/html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_KEY }}
          ignore_dev_requirements: "yes"
