name: run tests
env:
  METABASE_DETAILS: ${{ secrets.METABASE_DETAILS }}
on: [pull_request, release]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Pull the docker image
        run: docker pull joshnotable/metabase-tools:latest
      - name: Initialize docker container
        run: |
          docker run -d -p 3000:3000 --name metabase-tools-tests metabase/metabase:v0.44.0
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Code linting
        run: poetry run black .
      - name: Setup Metabase
        run: poetry run python ./tests/setup_metabase.py
      - name: Test with pytest
        run: poetry run pytest
