name: Test
on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11-dev"]
        metabase-version: ["v0.39.0.1","v0.40.8","v0.41.7","v0.42.4","v0.43.5","v0.44.2","latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Initialize docker container
        run: |
          docker pull metabase/metabase:${{ matrix.metabase-version }}
          docker run -d -p 3000:3000 metabase/metabase:${{ matrix.metabase-version }}
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry config virtualenvs.in-project true
          poetry config installer.parallel true
      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 120
          max_attempts: 3
          command: |
            poetry install --no-interaction --no-root --with dev
            poetry install --no-interaction
      - name: Setup Metabase
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 150
          max_attempts: 3
          command: poetry run python ./tests/setup_metabase.py
      - name: Test with pytest
        run: poetry run pytest --cov=metabase_tools --cov-report=xml --cov-fail-under=95
      - name: Upload log artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: temp/
