name: Test
on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
        metabase-version: ["v0.39.0.1", "v0.40.8", "v0.41.9", "v0.42.6", "v0.43.7.1", "v0.44.6.1", "v0.45.3", "latest"]

    runs-on: ${{ matrix.os }}
    env:
      MB_VERSION: ${{ matrix.metabase-version }}
      PY_VERSION: ${{ matrix.python-version }}
      SKIP: pylint,mypy

    steps:
      - uses: actions/checkout@v3
        id: checkout
      - name: Initialize docker containers
        id: docker
        run: docker compose up -d
      - name: Install Poetry
        id: poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry config virtualenvs.in-project true
          poetry config installer.parallel true
          poetry check
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        id: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        id: dependencies
        continue-on-error: true
        run: poetry install --no-interaction --with dev
      - name: Fix dependency errors
        id: dependency_errors
        run: poetry install --no-interaction --no-root --with dev
      - name: Enforce code formatting
        id: precommit
        continue-on-error: true
        run: poetry run pre-commit run --all-files
      - name: Enforce code style
        id: pylint
        continue-on-error: true
        run: poetry run pylint $(git ls-files './metabase_tools/*.py')
      - name: Enforce type hinting
        id: mypy
        continue-on-error: true
        run: poetry run mypy --strict $(git ls-files './metabase_tools/*.py')
      - name: Test with pytest
        id: pytest
        continue-on-error: true
        run: poetry run pytest --cov=metabase_tools --cov-report=xml --cov-report=html --cov-fail-under=95
      - name: Upload coverage to Codecov
        id: codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
      - name: Upload HTML coverage report
        id: coverage_upload
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage
          path: htmlcov/
      - name: Upload log artifacts
        id: log_upload
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: temp/
      - name: Determine failure or success
        id: resolve
        run: |
          if [[ ${{ steps.pytest.outcome }} == "failure" ]]; then echo 'pytest failure'; exit 1; fi
          if [[ ${{ steps.precommit.outcome }} == "failure" ]]; then echo 'precommit failure'; exit 1; fi
          if [[ ${{ steps.pylint.outcome }} == "failure" ]]; then echo 'pylint failure'; exit 1; fi
          if [[ ${{ steps.mypy.outcome }} == "failure" ]]; then echo 'mypy failure'; exit 1; fi

  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout
      - name: Install Poetry
        id: poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry config virtualenvs.in-project true
          poetry config installer.parallel true
          poetry check
      - name: Set up Python 3.10
        id: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        id: dependencies
        continue-on-error: true
        run: poetry install --no-interaction --with dev,docs
      - name: Build HTML
        id: sphinx
        run: poetry run sphinx-build -W -a -E -b html docs/source/ docs/build/html
      - name: Upload sphinx artifacts
        id: sphinx_upload
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/

  Analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
