name: Test
env:
  METABASE_DETAILS: ${{ secrets.METABASE_DETAILS }}
on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11-dev"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Initialize docker container
        run: |
          docker pull metabase/metabase:v0.39.0.1
          docker run -d -p 3000:3000 metabase/metabase:v0.39.0.1
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry config virtualenvs.in-project true
          poetry config installer.parallel true
      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 120
          max_attempts: 3
          command: |
            poetry install --no-interaction --no-root --with dev,docs
            poetry install --no-interaction
      - name: Enforce code formatting
        run: poetry run black .
      - name: Enforce code style
        run: poetry run pylint $(git ls-files './metabase_tools/*.py')
      - name: Enforce type hinting
        run: poetry run mypy --strict $(git ls-files './metabase_tools/*.py')
      - name: Setup Metabase
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 150
          max_attempts: 3
          command: poetry run python ./tests/setup_metabase.py
      - name: Test with pytest
        run: poetry run pytest --cov=metabase_tools --cov-report=xml --cov-fail-under=95
      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
      - name: Build HTML
        run: poetry run sphinx-build -a -E -b html docs/source/ docs/build/html
      - name: Upload sphinx artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/
      - name: Upload log artifacts
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: temp/
